const skills = [
    {
        title:"HTML",
        progress:'85%',
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg",
    },
    {
        title:"CSS",
        progress:'75%',
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg",
    },
    {
        title:"JavaScript",
        progress:'80%',
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-plain.svg",
    },
    {
        title:"Java",
        progress:'70%',
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg",
    },
    {
        title:"Python",
        progress:'60%',
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg",
    },
    {
        title:"React",
        progress:'75%',
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg",
    },
    {
        title:"Blender",
        progress:'55%',
        icon:"https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/blender/blender-original.svg",
    },
    {
        title:"Figma",
        progress:"60%",
        icon:"https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/figma/figma-original.svg",
    }
]